### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by peteshand** [RobertBorghese/Haxe-UnrealEngine5#5]
Hey, what are your thoughts on pulling the HaxeCompatibility out of the SampleProject? it kind of feels like a core of your project, so might be better suited to sit at the root at the same level as ExternGenerator, Externs and SampleProject

**Comment by SomeRanDev** [comment]
Yeah, that sounds good, the only thing is I've been thinking about removing the plugin all together? The `__boot_all()` function compiled in the plugin and the actual game code is different if you use any Haxe API in the game code, so it's kinda pointless to "initialize" everything in the plugin-side of things. 

Either need to move all the Haxe code into the plugin and let the compiled code be handled there... or find a way to "boot" at the start using just the game code. Was thinking about having every constructor check to see if Haxe is "booted" and booting it if it isn't, but that's a bit costly.... Hmmmm

*Or maybe it's possible to create a "Module" class in the game code and Unreal will also just let it run from inside there? I need to test that*

**Comment by SomeRanDev** [comment]
All right, made the changes I was referring to in the latest commit. Now instead of using a plugin, the Haxe code compiles to a separate module, so there's no longer a complicated "plugin build" step. Makes things much smoother. Maybe there's still some value to moving the module to the core of the project.. but then again maybe better to keep the SampleProject together so it's not too much work to get it set up and going?

What I could do maybe is create a Haxe script to setup and place everything in the correct spots, but then things will start to get complicated like Unreal.hx, which goes against the nature of this project. Simplicity and ease of use should be #1 in my opinion. Sooo I think I'm still leaning towards keeping things as they are, but I'm open to your thoughts and opinions!

**Comment by peteshand** [comment]
Yeah right, hmm yes I think I misunderstood the fact the the plugin's content was highly dependent on whatever Haxe you are compiling. I've given your updates a go. Works well, and the nice thing about removing the plugin is that this Haxe workflow can either be used as a project module, or within a plugin.
